chore: upgrade Rollup and related dependencies to latest version
react-dropzone/file-selector pull request #73
Opened 2024-02-29 14:42 UTC by jonkoops

**What kind of change does this PR introduce?**
- [ ] Bug Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Style
- [ ] Build
- [x] Chore
- [ ] Documentation
- [ ] CI

**Did you add tests for your changes?**
- [ ] Yes, my code is well tested
- [x] Not relevant

**If relevant, did you update the documentation?**
- [ ] Yes, I've updated the documentation
- [x] Not relevant

**Summary**
Upgrades Rollup and related dependencies to their respective latest version, and updated the Rollup configuration to match the latest conventions.

**Does this PR introduce a breaking change?**
No.

**Other information**
None.

2024-02-29 14:42 UTC, jonkoops commented on package.json
> -    "rollup-plugin-sourcemaps": "^0.6.3",
I've removed `rollup-plugin-sourcemaps`, as this functionality is now built into Rollup itself.

2024-02-29 14:43 UTC, jonkoops commented on package.json
> -    "rollup-plugin-terser": "^7.0.2",
I've replaced `rollup-plugin-terser` with `@rollup/plugin-terser`, which is the official Rollup plugin.

2024-02-29 14:47 UTC, jonkoops commented on rollup.config.mjs
This file is now an ECMAScript module (`.mjs`), as the new version of `camelcase` is a [pure ESM package](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), meaning it cannot be imported from CommonJS. Aside from that, it's also just good to start moving away from CommonJS.

2024-03-10 11:06 UTC, jonkoops commented
@rolandjitsu would it be possible to get this one merged?

2024-10-04 19:44 UTC, rolandjitsu requested changes
@jonkoops do you think you could fix the yarn.lock conflicts? Otherwise, this PR LGTM.

2024-10-06 15:24 UTC, jonkoops commented
Sure, I'll see what I can do. I'll also bump the versions since a couple of new releases have happened since.

2024-10-06 15:45 UTC, jonkoops commented on .github/workflows/test.yml
> +        run: yarn install --pure-lockfile --ignore-engines
Had to add `--ignore-engines` since some of the new dependencies require more modern Node.js versions, preventing dependencies from being installed.

2024-10-06 15:47 UTC, jonkoops commented
@rolandjitsu should be good to go like this, let me know what you think.

2024-10-07 19:41 UTC, merged